spring.application.name=eventManagement
server.port=${PORT:8085}
spring.data.mongodb.uri=mongodb+srv://ruushekas_db_user:qePkZ2KBWaOrjArH@cluster0.ldduwln.mongodb.net/student_events_db?retryWrites=true&w=majority